### ISSUE TITLE
falta @Table(uniqueConstraints= { 		@UniqueConstraint(columnNames="REPUESTO_ID, INTERVENCION_ID")	 	})

### ISSUE THREAD

**Issue by saritagrimal2** [ZenMaster91/uniovi.ri#3]
https://github.com/ZenMaster91/uniovi.ri/blob/85742202ed1b39b0d98ba659e1ed47a450164587/cws_model_to_java_skel/src/main/java/uo/ri/model/Sustitucion.java#L10

**Comment by thewillyhuman** [comment]
Working on

**Comment by thewillyhuman** [comment]
Fixed at 8c31027.
