### ISSUE TITLE
@Column(unique=true) private String nombre;

### ISSUE THREAD

**Issue by saritagrimal2** [ZenMaster91/uniovi.ri#4]
https://github.com/ZenMaster91/uniovi.ri/blob/85742202ed1b39b0d98ba659e1ed47a450164587/cws_model_to_java_skel/src/main/java/uo/ri/model/TipoVehiculo.java#L18

**Comment by thewillyhuman** [comment]
Working on.

**Comment by thewillyhuman** [comment]
Fixed at 8c31027.
